In [1]:
import torch
import numpy as np

In [4]:
x = [[1, 2],[3, 4]]
type(x)

list

In [5]:
x_tensor = torch.tensor(data)
print("This is a tensor", x_tensor)
x_tensor.type()

This is a tensor tensor([[1, 2],
        [3, 4]])


'torch.LongTensor'

In [8]:
# Create a tensor from numpy array
x_np = np.array(x)
print("This is a numpy array", x_np)
x_tensor_from_np = torch.from_numpy(x_np)
print("This is a tensor from numpy data", x_tensor_from_np)

This is a numpy array [[1 2]
 [3 4]]
This is a tensor from numpy data tensor([[1, 2],
        [3, 4]])


In [17]:
# Like in torch.randn_like means we want a tensor similar (with the same properties) to a specific tensor (here x_tensor)
x_tensor_one = torch.ones_like(x_tensor)
print("This is one tensor with the same properties as x\n",x_tensor_one)
x_tensor_randn = torch.randn_like(x_tensor, dtype = torch.float)
print("This is a random tensor with overriden data types\n", x_tensor_randn)

This is one tensor with the same properties as x
 tensor([[1, 1],
        [1, 1]])
This is a random tensor with overriden data types
 tensor([[-0.5206, -1.1377],
        [ 0.1618, -1.7204]])


In [23]:
# Shape is a tuple of tensor dimension
shape = (2,3,)
randn_tensor = torch.rand(shape)
one_tensor = torch.ones(shape)
print("This is random tensor with provided shape\n", 
      randn_tensor, "\nThis is one tensor with provided shape\n", one_tensor)

This is random tensor with provided shape
 tensor([[0.3278, 0.2557, 0.3542],
        [0.7441, 0.4219, 0.8716]]) 
This is one tensor with provided shape
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [36]:
# Attributes of a tensor 
shape = (2,3,)
tensor_a = torch.zeros(shape)
print(f"shape of tensor {tensor_a.shape}\ndata type of tensot is {tensor_a.dtype}\ndevice tensor is stored on {tensor_a.device}")

shape of tensor torch.Size([2, 3])
data type of tensot is torch.float32
device tensor is stored on cpu


In [37]:
# We move our tensor to the GPU if available
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

In [41]:
# Tensors have the same options as numpy arrays
tensor_b = torch.rand(3,5,)
print(tensor_b)
print(f"This is first row {tensor_b[0,:]}")
print(f"This is first column {tensor_b[:,0]}")
print(f"This is last row {tensor_b[-1,:]}")
print(f"This is last column {tensor_b[:,-1]}")

# Change the first row to be all zero
tensor_b[0,:] = 0
print(tensor_b)

tensor([[0.0724, 0.8722, 0.8238, 0.7579, 0.9402],
        [0.1533, 0.0929, 0.8305, 0.8898, 0.5231],
        [0.0154, 0.6516, 0.2234, 0.0148, 0.7223]])
This is first row tensor([0.0724, 0.8722, 0.8238, 0.7579, 0.9402])
This is first column tensor([0.0724, 0.1533, 0.0154])
This is last row tensor([0.0154, 0.6516, 0.2234, 0.0148, 0.7223])
This is last column tensor([0.9402, 0.5231, 0.7223])
tensor([[0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1533, 0.0929, 0.8305, 0.8898, 0.5231],
        [0.0154, 0.6516, 0.2234, 0.0148, 0.7223]])


In [58]:
# Joining a couple of tensors
print(tensor_a.shape)
print(tensor_b.shape)
tensor_c = torch.ones(2,5)
tensor_ac = torch.cat([tensor_a,tensor_c], dim = 1)
print("this is first tensor\n", tensor_a)
print("this is second tensor\n", tensor_c)
print("this is the joined tensor\n", tensor_ac)

torch.Size([2, 3])
torch.Size([3, 5])
this is first tensor
 tensor([[0., 0., 0.],
        [0., 0., 0.]])
this is second tensor
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
this is the joined tensor
 tensor([[0., 0., 0., 1., 1., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1., 1., 1.]])


In [62]:
tensor = torch.ones(4, 4)
tensor[:,1] = 0

y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

# This computes the element-wise product. z1, z2, z3 will have the same value
z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 = torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])