In [1]:
import torch
import numpy as np

In [4]:
x = [[1, 2],[3, 4]]
type(x)

list

In [5]:
x_tensor = torch.tensor(data)
print("This is a tensor", x_tensor)
x_tensor.type()

This is a tensor tensor([[1, 2],
        [3, 4]])


'torch.LongTensor'

In [8]:
# Create a tensor from numpy array
x_np = np.array(x)
print("This is a numpy array", x_np)
x_tensor_from_np = torch.from_numpy(x_np)
print("This is a tensor from numpy data", x_tensor_from_np)

This is a numpy array [[1 2]
 [3 4]]
This is a tensor from numpy data tensor([[1, 2],
        [3, 4]])


In [17]:
# Like in torch.randn_like means we want a tensor similar (with the same properties) to a specific tensor (here x_tensor)
x_tensor_one = torch.ones_like(x_tensor)
print("This is one tensor with the same properties as x\n",x_tensor_one)
x_tensor_randn = torch.randn_like(x_tensor, dtype = torch.float)
print("This is a random tensor with overriden data types\n", x_tensor_randn)

This is one tensor with the same properties as x
 tensor([[1, 1],
        [1, 1]])
This is a random tensor with overriden data types
 tensor([[-0.5206, -1.1377],
        [ 0.1618, -1.7204]])


In [23]:
# Shape is a tuple of tensor dimension
shape = (2,3,)
randn_tensor = torch.rand(shape)
one_tensor = torch.ones(shape)
print("This is random tensor with provided shape\n", 
      randn_tensor, "\nThis is one tensor with provided shape\n", one_tensor)

This is random tensor with provided shape
 tensor([[0.3278, 0.2557, 0.3542],
        [0.7441, 0.4219, 0.8716]]) 
This is one tensor with provided shape
 tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [36]:
# Attributes of a tensor 
shape = (2,3,)
tensor_a = torch.zeros(shape)
print(f"shape of tensor {tensor_a.shape}\ndata type of tensot is {tensor_a.dtype}\ndevice tensor is stored on {tensor_a.device}")

shape of tensor torch.Size([2, 3])
data type of tensot is torch.float32
device tensor is stored on cpu
